-- LEGACY SNAPSHOT — do not use this as the current Supabase schema.
-- database/current_db.sql is authoritative. This file is context only and is
-- not meant to be run; table order and constraints may not be executable.

CREATE TABLE public.staff_archived (
  staff_id bigint NOT NULL,
  staff_name character varying NOT NULL,
  staff_display_name character varying NOT NULL,
  staff_roblox_name character varying NOT NULL,
  staff_nationality character varying,
  staff_rank character varying NOT NULL,
  staff_days integer NOT NULL,
  staff_num_sesh_attend integer NOT NULL,
  hide_stats boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_archived_pkey PRIMARY KEY (staff_id)
);
CREATE TABLE public.staff_quota (
  quota_id character varying NOT NULL,
  profile_id uuid NOT NULL,
  quota_level smallint NOT NULL,
  quota_period character varying NOT NULL,
  quota_assist smallint NOT NULL DEFAULT 0,
  quota_co_host smallint NOT NULL DEFAULT 0,
  quota_session_host smallint NOT NULL DEFAULT 0,
  quota_event_host smallint NOT NULL DEFAULT 0,
  quota_event_co_host smallint NOT NULL DEFAULT 0,
  quota_remark text,
  quota_exemption boolean NOT NULL DEFAULT false,
  CONSTRAINT staff_quota_pkey PRIMARY KEY (quota_id),
  CONSTRAINT staff_quota_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.staff_timeline (
  profile_id uuid NOT NULL,
  days_as_staff integer NOT NULL,
  staff_nationality character varying,
  assist_auth_start date NOT NULL,
  assist_auth_end date NOT NULL,
  cohost_auth_start date,
  cohost_auth_end date,
  host_auth_start date,
  host_auth_end date,
  manager_start date,
  manager_end date,
  CONSTRAINT staff_timeline_pkey PRIMARY KEY (profile_id),
  CONSTRAINT staff_timeline_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  notif_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  category character varying NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  posted_by uuid,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (notif_id),
  CONSTRAINT notifications_posted_by_fkey FOREIGN KEY (posted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.event_upcoming (
  event_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  host text NOT NULL,
  co_hosts text,
  event_name character varying NOT NULL,
  event_date date NOT NULL,
  event_time time without time zone NOT NULL,
  game_or_location character varying NOT NULL,
  event_details text NOT NULL,
  event_additional_notes text,
  event_attendees text,
  CONSTRAINT event_upcoming_pkey PRIMARY KEY (event_id)
);
CREATE TABLE public.event_log_archives (
  event_id integer NOT NULL,
  host text NOT NULL,
  co_hosts text,
  event_name character varying NOT NULL,
  event_date date NOT NULL,
  event_time time without time zone NOT NULL,
  game_or_location character varying NOT NULL,
  event_details text NOT NULL,
  event_additional_notes text,
  event_attendees text NOT NULL,
  host_notes text,
  status character varying NOT NULL,
  CONSTRAINT event_log_archives_pkey PRIMARY KEY (event_id)
);
CREATE TABLE public.session_upcoming (
  session_id integer NOT NULL,
  session_status character varying NOT NULL,
  session_booked boolean NOT NULL,
  session_name character varying,
  session_desc text,
  session_duration character varying NOT NULL,
  num_slots smallint NOT NULL,
  trainer_assignment_mode character varying NOT NULL DEFAULT 'auto'::character varying CHECK (trainer_assignment_mode::text = ANY (ARRAY['auto'::character varying, 'manual'::character varying]::text[])),
  host character varying NOT NULL,
  co_host1 character varying,
  co_host2 character varying,
  co_host3 character varying,
  co_host4_supervisor character varying,
  assistant_1 character varying,
  assistant_2 character varying,
  assistant_3 character varying,
  assistant_4 character varying,
  additional_staff character varying,
  session_date date NOT NULL,
  session_time character varying NOT NULL,
  trainee_timer smallint NOT NULL,
  trainee_1_name character varying,
  trainee_1_discord character varying,
  trainee_1_discord_id bigint,
  trainee_1_zone smallint,
  trainee_1_note text,
  trainee_1_trainer_name character varying,
  trainee_2_name character varying,
  trainee_2_discord character varying,
  trainee_2_discord_id bigint,
  trainee_2_zone smallint,
  trainee_2_note text,
  trainee_2_trainer_name character varying,
  trainee_3_name character varying,
  trainee_3_discord character varying,
  trainee_3_discord_id bigint,
  trainee_3_zone smallint,
  trainee_3_note text,
  trainee_3_trainer_name character varying,
  trainee_4_name character varying,
  trainee_4_discord character varying,
  trainee_4_discord_id bigint,
  trainee_4_zone smallint,
  trainee_4_note text,
  trainee_4_trainer_name character varying,
  trainee_5_name character varying,
  trainee_5_discord character varying,
  trainee_5_discord_id bigint,
  trainee_5_zone smallint,
  trainee_5_note text,
  trainee_5_trainer_name character varying,
  trainee_6_name character varying,
  trainee_6_discord character varying,
  trainee_6_discord_id bigint,
  trainee_6_zone smallint,
  trainee_6_note text,
  trainee_6_trainer_name character varying,
  trainee_7_name character varying,
  trainee_7_discord character varying,
  trainee_7_discord_id bigint,
  trainee_7_zone smallint,
  trainee_7_note text,
  trainee_7_trainer_name character varying,
  trainee_8_name character varying,
  trainee_8_discord character varying,
  trainee_8_discord_id bigint,
  trainee_8_zone smallint,
  trainee_8_note text,
  trainee_8_trainer_name character varying,
  trainee_9_name character varying,
  trainee_9_discord character varying,
  trainee_9_discord_id bigint,
  trainee_9_zone smallint,
  trainee_9_note text,
  trainee_9_trainer_name character varying,
  trainee_10_name character varying,
  trainee_10_discord character varying,
  trainee_10_discord_id bigint,
  trainee_10_zone smallint,
  trainee_10_note text,
  trainee_10_trainer_name character varying,
  additional_notes text,
  CONSTRAINT session_upcoming_pkey PRIMARY KEY (session_id)
);
CREATE TABLE public.session_ongoing (
  session_id integer NOT NULL,
  session_status character varying NOT NULL,
  session_name character varying,
  session_desc text,
  session_duration character varying NOT NULL,
  num_slots smallint NOT NULL,
  trainer_assignment_mode character varying NOT NULL DEFAULT 'auto'::character varying CHECK (trainer_assignment_mode::text = ANY (ARRAY['auto'::character varying, 'manual'::character varying]::text[])),
  staff_attendance character varying NOT NULL,
  session_date date NOT NULL,
  session_time character varying NOT NULL,
  started_at timestamp with time zone,
  trainee_timer smallint NOT NULL,
  trainee_1_name character varying,
  trainee_1_discord character varying,
  trainee_1_discord_id bigint,
  trainee_1_zone smallint,
  trainee_1_note text,
  trainee_1_trainer_name character varying,
  trainee_2_name character varying,
  trainee_2_discord character varying,
  trainee_2_discord_id bigint,
  trainee_2_zone smallint,
  trainee_2_note text,
  trainee_2_trainer_name character varying,
  trainee_3_name character varying,
  trainee_3_discord character varying,
  trainee_3_discord_id bigint,
  trainee_3_zone smallint,
  trainee_3_note text,
  trainee_3_trainer_name character varying,
  trainee_4_name character varying,
  trainee_4_discord character varying,
  trainee_4_discord_id bigint,
  trainee_4_zone smallint,
  trainee_4_note text,
  trainee_4_trainer_name character varying,
  trainee_5_name character varying,
  trainee_5_discord character varying,
  trainee_5_discord_id bigint,
  trainee_5_zone smallint,
  trainee_5_note text,
  trainee_5_trainer_name character varying,
  trainee_6_name character varying,
  trainee_6_discord character varying,
  trainee_6_discord_id bigint,
  trainee_6_zone smallint,
  trainee_6_note text,
  trainee_6_trainer_name character varying,
  trainee_7_name character varying,
  trainee_7_discord character varying,
  trainee_7_discord_id bigint,
  trainee_7_zone smallint,
  trainee_7_note text,
  trainee_7_trainer_name character varying,
  trainee_8_name character varying,
  trainee_8_discord character varying,
  trainee_8_discord_id bigint,
  trainee_8_zone smallint,
  trainee_8_note text,
  trainee_8_trainer_name character varying,
  trainee_9_name character varying,
  trainee_9_discord character varying,
  trainee_9_discord_id bigint,
  trainee_9_zone smallint,
  trainee_9_note text,
  trainee_9_trainer_name character varying,
  trainee_10_name character varying,
  trainee_10_discord character varying,
  trainee_10_discord_id bigint,
  trainee_10_zone smallint,
  trainee_10_note text,
  trainee_10_trainer_name character varying,
  trainee_attendance character varying NOT NULL,
  additional_notes text,
  live_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT session_ongoing_pkey PRIMARY KEY (session_id)
);
CREATE TABLE public.session_post_logs (
  session_id integer NOT NULL,
  session_name character varying,
  session_desc text,
  session_status character varying,
  session_date date,
  session_duration_expected character varying,
  session_runtime_actual integer,
  num_slots smallint,
  actual_slots_provided smallint,
  additional_notes text,
  main_ast_notes text,
  started time without time zone,
  ended time without time zone,
  concluded_at timestamp with time zone,
  CONSTRAINT session_post_logs_pkey PRIMARY KEY (session_id)
);
CREATE TABLE public.session_staff_logs (
  session_id integer NOT NULL,
  host character varying NOT NULL,
  cohost_1 character varying,
  cohost_2 character varying,
  cohost_3 character varying,
  cohost_4_supervisor character varying,
  assistant_1 character varying,
  assistant_2 character varying,
  assistant_3 character varying,
  assistant_4 character varying,
  full_staff_json jsonb,
  CONSTRAINT session_staff_logs_pkey PRIMARY KEY (session_id)
);
CREATE TABLE public.session_full_logs (
  log_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  session_id integer NOT NULL,
  trainee_id bigint NOT NULL,
  trainee_roblox character varying NOT NULL,
  trainee_zone smallint NOT NULL,
  trainee_attendance boolean NOT NULL,
  trainer_id bigint NOT NULL,
  trainee_notes text,
  staff_notes text,
  trainee_assessed integer NOT NULL,
  trainee_feedback boolean NOT NULL,
  feedback_sent boolean NOT NULL,
  CONSTRAINT session_full_logs_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.session_driver_logs (
  log_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  session_id integer NOT NULL,
  discord_username character varying,
  roblox_name character varying,
  attendance boolean NOT NULL DEFAULT false,
  CONSTRAINT session_driver_logs_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.session_feedback_logs (
  log_id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  session_id integer NOT NULL,
  trainee_id bigint NOT NULL,
  trainer_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  trains smallint,
  setup text,
  conflict text,
  priority text,
  rbtiming text,
  overall text,
  notes text,
  setup_seconds integer,
  CONSTRAINT session_feedback_logs_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  discord_id text UNIQUE,
  discord_username text NOT NULL DEFAULT ''::text,
  discord_avatar_url text,
  roblox_id bigint,
  roblox_username text,
  roblox_verified_at timestamp with time zone,
  nationality text,
  num_sessions_attended smallint NOT NULL DEFAULT 0,
  hide_stats boolean NOT NULL DEFAULT false,
  notif_prefs jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.staff_profiles (
  id uuid NOT NULL,
  staff_rank text NOT NULL,
  staff_joined date NOT NULL,
  staff_loa boolean NOT NULL DEFAULT false,
  staff_quota_met boolean NOT NULL DEFAULT false,
  staff_perm_level smallint NOT NULL DEFAULT 0,
  CONSTRAINT staff_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT staff_profiles_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);
CREATE TABLE public.site_admins (
  id uuid NOT NULL,
  admin_role text NOT NULL DEFAULT 'developer'::text CHECK (admin_role = ANY (ARRAY['owner'::text, 'developer'::text, 'moderator'::text])),
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_admins_pkey PRIMARY KEY (id),
  CONSTRAINT site_admins_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);
